-- CreateTable
CREATE TABLE `cacheLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `hit` BOOLEAN NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
